name: Continuous Integration
on: [push]

jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy source-code
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: 22
          KEY: ${{ secrets.KEY }}
        with:
          source: "*"
          target: "."
